### ISSUE TITLE
Slider Speed

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/bookrev-lite#27]
We have a message from a client. "Any way to adjust the slider speed?"

At the moment we do not have this possibility. I think it's a good idea to integrate this feature. @vncatalin @ineagu

**Comment by ineagu** [comment]
Is a too specific feature, we don't really offer this level of customization, we want simple themes.

We only take suggestions into consideration when2-3 people asked for it. 

In this case if too many prople complain we will reduce the speed of the slider, not offer a customization for a simple thing like this
