### ISSUE TITLE
Give shop some padding

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/bookrev-lite#63]
@abaicus the shop products are stuck to the sides, also is it normal for the widgets to be at the bottom of the shop?

**Comment by rodica-andronache** [comment]
@stefan-cotitosu if you want to offer some basic compatibility here, you should at least add the products in the main container, and remove the sidebar.
This can be done using hooks something like this https://github.com/Codeinwp/hestia-pro/blob/production/inc/woocommerce/hooks.php#L15-L17 http://prntscr.com/fyfknd
