### ISSUE TITLE
Wrong assigned color

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/bookrev-lite#65]
![image](https://cloud.githubusercontent.com/assets/10324144/26759041/bda5586c-48bf-11e7-9f00-6d0f8a641d32.png)

The highlight of the day background color is being pulled from the articles background color

**Comment by stefan-cotitosu** [comment]
A post should be sticky in order to be displayed in Highlight of the day section.

![bookrev_hotd_color](https://user-images.githubusercontent.com/26867648/27685465-f344f86c-5cd6-11e7-9b50-bb6d793862e6.png)
