### ISSUE TITLE
slider still looks bad on mobile

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/bookrev-lite#9]
Check this on mobile : http://dev2.themeisle.com/bookrev-lite/, slider still looks bad

**Comment by ineagu** [comment]
@vncatalin aici inca se vede rau . Poti inainte sa faci commit, sa faci iarasi fork ? ( stergi fork-ul initial si faci altul ) ca sa ai ultima versiune si sa nu mai fie conflicte.

**Comment by vncatalin** [comment]
@ineagu Nu stiu exact la ce te referi ca se vede rau, daca te referi ca nu apare coperta cartii este pt ca am scos-o de tot, nu are cum sa incapa si coperta si continutul slideului. http://i.imgur.com/CcRPlHV.png

Poti urca un screenshot te rog ?

**Comment by ineagu** [comment]
cand ai prea mult text acolo la excerpt se vede ok pt tine ?
